name: Deploy To Server

on:
  push:
    branches: [ main ]

jobs:
  test:
    name: Run all tests
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:11
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
        ports:
        - 5432:5432
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5
    steps:
      - uses: actions/checkout@v2
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.6.6
          bundler-cache: true
      - name: Setup databases
        env:
          DATABASE_USERNAME: postgres
          DATABASE_PASSWORD: postgres
          RAILS_ENV: test
        run: bundle exec rake db:setup
      - name: Test with RSpec
        env:
          DATABASE_USERNAME: postgres
          DATABASE_PASSWORD: postgres
          RAILS_ENV: test
        run: bundle exec rspec
